[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "xlsx", "multer", "cors", "express", "serverless-http"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
